update to new version

diff --git a/portknock b/portknock
--- a/portknock
+++ b/portknock
@@ -2,39 +2,53 @@
 
 # Port Knocker
 #
-# 1 - Append this code to your .bashrc or .bash_profile file
-# 2 - Create a .portknocks file in your home directory with a list like
-# host1 port1
-# host1 port2
+# 1 - Put this code in ~/.bashrc.d/portknock
+# 2 - source that path in your .bashrc or .bash_profile
+# 3 - Create a ~/.portknock directory and one or more files in it with
+#     entries like:
+# host_regexp port1,port2,...,portN
+#     (lines with # are ignored)
 # ...
-# host1 portN
-# host2 port1
-# ...
-# 3 - You must open a new terminal session to use the new function
-# 4 - Use it as you would use the ssh command
-# ssh user@server => pssh user@server
+# 4 - You must open a new terminal session to use the new function
+# 5 - Use it as you would use the ssh command
+#     ssh user@server => pssh user@server
+#   - or with psshproxy as a ProxyCommand in .ssh/config
+#     ProxyCommand psshproxy %h %p
 #
 # It accepts the usual options of the SSH program
 
-PORTKNOCKSDIR=~/.portknocks
+PORTKNOCKDIR=~/.portknock
 
 portknock() {
   HOST=$1
-  CNT=1
 
-  if ! grep ^$HOST $PORTKNOCKSDIR/* > /dev/null 2>&1
-  then
-    echo "ERROR: please specify a port knock sequence for $HOST in $PORTKNOCKSDIR"
-    return 1
-  fi
-
-  grep ^$HOST $PORTKNOCKSDIR/* | awk '{ for(i=2; i <= NF; i++) printf "%s\n", $i}' | \
-  while read PORT
+  old_IFS=$IFS
+  IFS=$'\n'
+  for line in `cat $PORTKNOCKDIR/*`
   do
-    # echo "Knocking $HOST ($CNT)"
-    nc -w 1 $HOST $PORT
-    ((CNT++))
+    first=`echo $line | cut -c1`
+    if test x$first == x#
+    then
+      continue
+    fi
+
+    regexp=`echo $line | cut -d' ' -f1`
+    ports=`echo $line | cut -d' ' -f2`
+
+    echo $HOST | grep -E $regexp > /dev/null 2>&1
+    if test $? == 0
+    then
+      IFS=$old_IFS
+      for port in `echo $ports | cut -d, -f1- --output-delimiter=' '`
+      do
+        nc -w 1 $HOST $port
+      done
+      return 0
+    fi
   done
+
+  echo "ERROR: please specify a port knock sequence for $HOST in $PORTKNOCKDIR"
+  return 1
 }
 
 pssh() {
@@ -46,7 +60,7 @@ pssh() {
   HOST=${@:$OPTIND:1}
   HOST=${HOST#*@}
 
-  portknock $HOST || return 
+  portknock $HOST || return
   ssh $*
 }
 
